[service]
name = "the new backend service n°1"
version = "1.0.0" #it is a private field
db = "mongo"
 
 
  #[service.#features] # {features} are specific features of the service and the logical part algorithm
  [service.refresh]
  # paginateLimit = 10
  nbPerRefresh = 10
  retryInterval = 30
 
    [service.refresh.vDev]
    # the virtual device list
    # task's periodic interval
    tickerInterval = 5
    # performing condition
    window = 15
 
  [service.event]
 
    [service.event.emitters]
 
      [service.event.emitters.streams]
      virtualDeviceData = "VIRTUAL_DEVICE_DATA_STREAM"
 
    [service.event.consumers]
    group = "connectors_api_gateway"
    name = "connectors_api_gateway_1"
    maxAccessStream = 10.0
 
      [service.event.consumers.streams]
      command = "DEVICE_COMMAND_STREAM"
      data = "DEVICE_DATA_STREAM"
      properties = "DEVICE_PROPERTIES_STREAM"
      new = "NEW_DEVICE_STREAM"
      delete = "REMOVED_DEVICE_STREAM"
      virtualDevices = "VIRTUAL_DEVICE_PAIRING_STREAM"
 
[server]
 
  #[server.#serverType] # {serverType} : independant servers, like public api, private api, mobile api, partenaire api
  [server.public]
  protocol = "http"
  host = "localhost"
  port = 8080
  allow_origin = "*"
 
    [server.public.tls]
 
      [server.public.tls.cert]
      cert_path = ""
      key_path = ""
      ca_chain_path = ""
 
    [server.public.authentication]
    type = "apiKey"
    apiKey = "piha8WgccS"
    protocol = "https"
    host = "keycloak.keycloak-qualif.sahrd.io"
    port = 443
 
  [server.private]
  protocol = "https"
  host = "localhost"
  port = 8443
  allow_origin = "*"
 
    [server.private.tls]
 
      [server.private.tls.cert]
      cert_path = ""
      key_path = ""
      ca_chain_path = ""
 
    [server.private.authentication]
    type = "apiKey"
    apiKey = "UMZrdxk9RANmya88"
 
[clients] # customized or implementation of client libs, mqtt, netatmo, etc
 
  [clients.netatmo] 
  partnerId = "ORANGE-SMLF"
  apiKey = "ORANGE-SMLF-NETATMO-1234"
  host = ""
 
  [clients.eventstore]
  host = ""
  port = 6379
  password = ""
 
  [clients.mqtt]
    messageServer = "vernemq"
   
    [clients.mqtt.connection]
      protocol = "ssl"
      protocolId = "MQTT"
      host = ""
      port = 8883
      username = ""
      password = ""
      certPath = ""
      connectTimeout = 3000
      rejectUnauthorized = true
 
[store]
 
  [clients.store.postgres]
    name = ""
    username = ""
    password = ""
    host = ""
    port = 5432
 
  [store.mongo]
  username = ""
  password = ""
  db = ""
 
    [[store.mongo.hosts]]
    host = ""
    port = 27017
    [[store.mongo.hosts]]
    host = ""
    port = 27017   
 
[logger]
level = "debug"
colorized = true
 
[monitoring]
 
  [monitoring.prometheus]
  port = 7777
  prefix = ""